namespace Orion.Protocol.Enums;
public enum EntityIdentifier : byte
{
    Balloon,
    FallingBlock,
    Vindicator,
    VillagerV2,
    IceBomb,
    Cat,
    Bee,
    WanderingTrader,
    Wolf,
    Rabbit,
    Sniffer,
    Tadpole,
    WindChargeProjectile,
    Sheep,
    Witch,
    Zoglin,
    Skeleton,
    Cow,
    Ravager,
    Mooshroom,
    Allay,
    IronGolem,
    Dolphin,
    Breeze,
    TraderLlama,
    Turtle,
    Tropicalfish,
    PolarBear,
    Chicken,
    Panda,
    Slime,
    Pillager,
    Mule,
    ZombieVillager,
    Arrow,
    Llama,
    Horse,
    Donkey,
    Bogged,
    Camel,
    BreezeWindChargeProjectile,
    ZombieHorse,
    Zombie,
    Villager,
    Strider,
    OminousItemSpawner,
    Warden,
    Agent,
    Stray,
    Spider,
    Player,
    SmallFireball,
    SkeletonHorse,
    Husk,
    Hoglin,
    EnderCrystal,
    Silverfish,
    Armadillo,
    Piglin,
    Guardian,
    Wither,
    Vex,
    Pig,
    Parrot,
    Ocelot,
    Blaze,
    Goat,
    Frog,
    Fox,
    CaveSpider,
    WitherSkeleton,
    Squid,
    Shulker,
    Salmon,
    Creeper,
    Pufferfish,
    PiglinBrute,
    Phantom,
    Npc,
    MagmaCube,
    LlamaSpit,
    GlowSquid,
    EnderDragon,
    Ghast,
    Cod,
    EvocationIllager,
    Endermite,
    Enderman,
    ElderGuardian,
    Drowned,
    Bat,
    Axolotl,
    XpOrb,
    ZombieVillagerV2,
    ZombiePigman,
    SnowGolem,
    Fireball,
    ChestBoat,
    Boat,
    ShulkerBullet,
    XpBottle,
    Tnt,
    SplashPotion,
    LingeringPotion,
    WitherSkullDangerous,
    WitherSkull,
    ThrownTrident,
    Snowball,
    FishingHook,
    EnderPearl,
    Egg,
    DragonFireball,
    ArmorStand,
    LightningBolt,
    TripodCamera,
    TntMinecart,
    Minecart,
    HopperMinecart,
    FireworksRocket,
    EyeOfEnderSignal,
    CommandBlockMinecart,
    ChestMinecart,
    AreaEffectCloud,
    Creaking,
    Item,
    Unknown = 255,
}

public static class EntityIdentifierExtensions
{
    public static EntityIdentifier FromString(string value) => value switch
    {
        "minecraft:balloon" => EntityIdentifier.Balloon,
        "minecraft:falling_block" => EntityIdentifier.FallingBlock,
        "minecraft:vindicator" => EntityIdentifier.Vindicator,
        "minecraft:villager_v2" => EntityIdentifier.VillagerV2,
        "minecraft:ice_bomb" => EntityIdentifier.IceBomb,
        "minecraft:cat" => EntityIdentifier.Cat,
        "minecraft:bee" => EntityIdentifier.Bee,
        "minecraft:wandering_trader" => EntityIdentifier.WanderingTrader,
        "minecraft:wolf" => EntityIdentifier.Wolf,
        "minecraft:rabbit" => EntityIdentifier.Rabbit,
        "minecraft:sniffer" => EntityIdentifier.Sniffer,
        "minecraft:tadpole" => EntityIdentifier.Tadpole,
        "minecraft:wind_charge_projectile" => EntityIdentifier.WindChargeProjectile,
        "minecraft:sheep" => EntityIdentifier.Sheep,
        "minecraft:witch" => EntityIdentifier.Witch,
        "minecraft:zoglin" => EntityIdentifier.Zoglin,
        "minecraft:skeleton" => EntityIdentifier.Skeleton,
        "minecraft:cow" => EntityIdentifier.Cow,
        "minecraft:ravager" => EntityIdentifier.Ravager,
        "minecraft:mooshroom" => EntityIdentifier.Mooshroom,
        "minecraft:allay" => EntityIdentifier.Allay,
        "minecraft:iron_golem" => EntityIdentifier.IronGolem,
        "minecraft:dolphin" => EntityIdentifier.Dolphin,
        "minecraft:breeze" => EntityIdentifier.Breeze,
        "minecraft:trader_llama" => EntityIdentifier.TraderLlama,
        "minecraft:turtle" => EntityIdentifier.Turtle,
        "minecraft:tropicalfish" => EntityIdentifier.Tropicalfish,
        "minecraft:polar_bear" => EntityIdentifier.PolarBear,
        "minecraft:chicken" => EntityIdentifier.Chicken,
        "minecraft:panda" => EntityIdentifier.Panda,
        "minecraft:slime" => EntityIdentifier.Slime,
        "minecraft:pillager" => EntityIdentifier.Pillager,
        "minecraft:mule" => EntityIdentifier.Mule,
        "minecraft:zombie_villager" => EntityIdentifier.ZombieVillager,
        "minecraft:arrow" => EntityIdentifier.Arrow,
        "minecraft:llama" => EntityIdentifier.Llama,
        "minecraft:horse" => EntityIdentifier.Horse,
        "minecraft:donkey" => EntityIdentifier.Donkey,
        "minecraft:bogged" => EntityIdentifier.Bogged,
        "minecraft:camel" => EntityIdentifier.Camel,
        "minecraft:breeze_wind_charge_projectile" => EntityIdentifier.BreezeWindChargeProjectile,
        "minecraft:zombie_horse" => EntityIdentifier.ZombieHorse,
        "minecraft:zombie" => EntityIdentifier.Zombie,
        "minecraft:villager" => EntityIdentifier.Villager,
        "minecraft:strider" => EntityIdentifier.Strider,
        "minecraft:ominous_item_spawner" => EntityIdentifier.OminousItemSpawner,
        "minecraft:warden" => EntityIdentifier.Warden,
        "minecraft:agent" => EntityIdentifier.Agent,
        "minecraft:stray" => EntityIdentifier.Stray,
        "minecraft:spider" => EntityIdentifier.Spider,
        "minecraft:player" => EntityIdentifier.Player,
        "minecraft:small_fireball" => EntityIdentifier.SmallFireball,
        "minecraft:skeleton_horse" => EntityIdentifier.SkeletonHorse,
        "minecraft:husk" => EntityIdentifier.Husk,
        "minecraft:hoglin" => EntityIdentifier.Hoglin,
        "minecraft:ender_crystal" => EntityIdentifier.EnderCrystal,
        "minecraft:silverfish" => EntityIdentifier.Silverfish,
        "minecraft:armadillo" => EntityIdentifier.Armadillo,
        "minecraft:piglin" => EntityIdentifier.Piglin,
        "minecraft:guardian" => EntityIdentifier.Guardian,
        "minecraft:wither" => EntityIdentifier.Wither,
        "minecraft:vex" => EntityIdentifier.Vex,
        "minecraft:pig" => EntityIdentifier.Pig,
        "minecraft:parrot" => EntityIdentifier.Parrot,
        "minecraft:ocelot" => EntityIdentifier.Ocelot,
        "minecraft:blaze" => EntityIdentifier.Blaze,
        "minecraft:goat" => EntityIdentifier.Goat,
        "minecraft:frog" => EntityIdentifier.Frog,
        "minecraft:fox" => EntityIdentifier.Fox,
        "minecraft:cave_spider" => EntityIdentifier.CaveSpider,
        "minecraft:wither_skeleton" => EntityIdentifier.WitherSkeleton,
        "minecraft:squid" => EntityIdentifier.Squid,
        "minecraft:shulker" => EntityIdentifier.Shulker,
        "minecraft:salmon" => EntityIdentifier.Salmon,
        "minecraft:creeper" => EntityIdentifier.Creeper,
        "minecraft:pufferfish" => EntityIdentifier.Pufferfish,
        "minecraft:piglin_brute" => EntityIdentifier.PiglinBrute,
        "minecraft:phantom" => EntityIdentifier.Phantom,
        "minecraft:npc" => EntityIdentifier.Npc,
        "minecraft:magma_cube" => EntityIdentifier.MagmaCube,
        "minecraft:llama_spit" => EntityIdentifier.LlamaSpit,
        "minecraft:glow_squid" => EntityIdentifier.GlowSquid,
        "minecraft:ender_dragon" => EntityIdentifier.EnderDragon,
        "minecraft:ghast" => EntityIdentifier.Ghast,
        "minecraft:cod" => EntityIdentifier.Cod,
        "minecraft:evocation_illager" => EntityIdentifier.EvocationIllager,
        "minecraft:endermite" => EntityIdentifier.Endermite,
        "minecraft:enderman" => EntityIdentifier.Enderman,
        "minecraft:elder_guardian" => EntityIdentifier.ElderGuardian,
        "minecraft:drowned" => EntityIdentifier.Drowned,
        "minecraft:bat" => EntityIdentifier.Bat,
        "minecraft:axolotl" => EntityIdentifier.Axolotl,
        "minecraft:xp_orb" => EntityIdentifier.XpOrb,
        "minecraft:zombie_villager_v2" => EntityIdentifier.ZombieVillagerV2,
        "minecraft:zombie_pigman" => EntityIdentifier.ZombiePigman,
        "minecraft:snow_golem" => EntityIdentifier.SnowGolem,
        "minecraft:fireball" => EntityIdentifier.Fireball,
        "minecraft:chest_boat" => EntityIdentifier.ChestBoat,
        "minecraft:boat" => EntityIdentifier.Boat,
        "minecraft:shulker_bullet" => EntityIdentifier.ShulkerBullet,
        "minecraft:xp_bottle" => EntityIdentifier.XpBottle,
        "minecraft:tnt" => EntityIdentifier.Tnt,
        "minecraft:splash_potion" => EntityIdentifier.SplashPotion,
        "minecraft:lingering_potion" => EntityIdentifier.LingeringPotion,
        "minecraft:wither_skull_dangerous" => EntityIdentifier.WitherSkullDangerous,
        "minecraft:wither_skull" => EntityIdentifier.WitherSkull,
        "minecraft:thrown_trident" => EntityIdentifier.ThrownTrident,
        "minecraft:snowball" => EntityIdentifier.Snowball,
        "minecraft:fishing_hook" => EntityIdentifier.FishingHook,
        "minecraft:ender_pearl" => EntityIdentifier.EnderPearl,
        "minecraft:egg" => EntityIdentifier.Egg,
        "minecraft:dragon_fireball" => EntityIdentifier.DragonFireball,
        "minecraft:armor_stand" => EntityIdentifier.ArmorStand,
        "minecraft:lightning_bolt" => EntityIdentifier.LightningBolt,
        "minecraft:tripod_camera" => EntityIdentifier.TripodCamera,
        "minecraft:tnt_minecart" => EntityIdentifier.TntMinecart,
        "minecraft:minecart" => EntityIdentifier.Minecart,
        "minecraft:hopper_minecart" => EntityIdentifier.HopperMinecart,
        "minecraft:fireworks_rocket" => EntityIdentifier.FireworksRocket,
        "minecraft:eye_of_ender_signal" => EntityIdentifier.EyeOfEnderSignal,
        "minecraft:command_block_minecart" => EntityIdentifier.CommandBlockMinecart,
        "minecraft:chest_minecart" => EntityIdentifier.ChestMinecart,
        "minecraft:area_effect_cloud" => EntityIdentifier.AreaEffectCloud,
        "minecraft:creaking" => EntityIdentifier.Creaking,
        "minecraft:item" => EntityIdentifier.Item,
        _ => EntityIdentifier.Unknown,
    };

    public static string ToIdentifierString(this EntityIdentifier identifier) => identifier switch
    {
        EntityIdentifier.Balloon => "minecraft:balloon",
        EntityIdentifier.FallingBlock => "minecraft:falling_block",
        EntityIdentifier.Vindicator => "minecraft:vindicator",
        EntityIdentifier.VillagerV2 => "minecraft:villager_v2",
        EntityIdentifier.IceBomb => "minecraft:ice_bomb",
        EntityIdentifier.Cat => "minecraft:cat",
        EntityIdentifier.Bee => "minecraft:bee",
        EntityIdentifier.WanderingTrader => "minecraft:wandering_trader",
        EntityIdentifier.Wolf => "minecraft:wolf",
        EntityIdentifier.Rabbit => "minecraft:rabbit",
        EntityIdentifier.Sniffer => "minecraft:sniffer",
        EntityIdentifier.Tadpole => "minecraft:tadpole",
        EntityIdentifier.WindChargeProjectile => "minecraft:wind_charge_projectile",
        EntityIdentifier.Sheep => "minecraft:sheep",
        EntityIdentifier.Witch => "minecraft:witch",
        EntityIdentifier.Zoglin => "minecraft:zoglin",
        EntityIdentifier.Skeleton => "minecraft:skeleton",
        EntityIdentifier.Cow => "minecraft:cow",
        EntityIdentifier.Ravager => "minecraft:ravager",
        EntityIdentifier.Mooshroom => "minecraft:mooshroom",
        EntityIdentifier.Allay => "minecraft:allay",
        EntityIdentifier.IronGolem => "minecraft:iron_golem",
        EntityIdentifier.Dolphin => "minecraft:dolphin",
        EntityIdentifier.Breeze => "minecraft:breeze",
        EntityIdentifier.TraderLlama => "minecraft:trader_llama",
        EntityIdentifier.Turtle => "minecraft:turtle",
        EntityIdentifier.Tropicalfish => "minecraft:tropicalfish",
        EntityIdentifier.PolarBear => "minecraft:polar_bear",
        EntityIdentifier.Chicken => "minecraft:chicken",
        EntityIdentifier.Panda => "minecraft:panda",
        EntityIdentifier.Slime => "minecraft:slime",
        EntityIdentifier.Pillager => "minecraft:pillager",
        EntityIdentifier.Mule => "minecraft:mule",
        EntityIdentifier.ZombieVillager => "minecraft:zombie_villager",
        EntityIdentifier.Arrow => "minecraft:arrow",
        EntityIdentifier.Llama => "minecraft:llama",
        EntityIdentifier.Horse => "minecraft:horse",
        EntityIdentifier.Donkey => "minecraft:donkey",
        EntityIdentifier.Bogged => "minecraft:bogged",
        EntityIdentifier.Camel => "minecraft:camel",
        EntityIdentifier.BreezeWindChargeProjectile => "minecraft:breeze_wind_charge_projectile",
        EntityIdentifier.ZombieHorse => "minecraft:zombie_horse",
        EntityIdentifier.Zombie => "minecraft:zombie",
        EntityIdentifier.Villager => "minecraft:villager",
        EntityIdentifier.Strider => "minecraft:strider",
        EntityIdentifier.OminousItemSpawner => "minecraft:ominous_item_spawner",
        EntityIdentifier.Warden => "minecraft:warden",
        EntityIdentifier.Agent => "minecraft:agent",
        EntityIdentifier.Stray => "minecraft:stray",
        EntityIdentifier.Spider => "minecraft:spider",
        EntityIdentifier.Player => "minecraft:player",
        EntityIdentifier.SmallFireball => "minecraft:small_fireball",
        EntityIdentifier.SkeletonHorse => "minecraft:skeleton_horse",
        EntityIdentifier.Husk => "minecraft:husk",
        EntityIdentifier.Hoglin => "minecraft:hoglin",
        EntityIdentifier.EnderCrystal => "minecraft:ender_crystal",
        EntityIdentifier.Silverfish => "minecraft:silverfish",
        EntityIdentifier.Armadillo => "minecraft:armadillo",
        EntityIdentifier.Piglin => "minecraft:piglin",
        EntityIdentifier.Guardian => "minecraft:guardian",
        EntityIdentifier.Wither => "minecraft:wither",
        EntityIdentifier.Vex => "minecraft:vex",
        EntityIdentifier.Pig => "minecraft:pig",
        EntityIdentifier.Parrot => "minecraft:parrot",
        EntityIdentifier.Ocelot => "minecraft:ocelot",
        EntityIdentifier.Blaze => "minecraft:blaze",
        EntityIdentifier.Goat => "minecraft:goat",
        EntityIdentifier.Frog => "minecraft:frog",
        EntityIdentifier.Fox => "minecraft:fox",
        EntityIdentifier.CaveSpider => "minecraft:cave_spider",
        EntityIdentifier.WitherSkeleton => "minecraft:wither_skeleton",
        EntityIdentifier.Squid => "minecraft:squid",
        EntityIdentifier.Shulker => "minecraft:shulker",
        EntityIdentifier.Salmon => "minecraft:salmon",
        EntityIdentifier.Creeper => "minecraft:creeper",
        EntityIdentifier.Pufferfish => "minecraft:pufferfish",
        EntityIdentifier.PiglinBrute => "minecraft:piglin_brute",
        EntityIdentifier.Phantom => "minecraft:phantom",
        EntityIdentifier.Npc => "minecraft:npc",
        EntityIdentifier.MagmaCube => "minecraft:magma_cube",
        EntityIdentifier.LlamaSpit => "minecraft:llama_spit",
        EntityIdentifier.GlowSquid => "minecraft:glow_squid",
        EntityIdentifier.EnderDragon => "minecraft:ender_dragon",
        EntityIdentifier.Ghast => "minecraft:ghast",
        EntityIdentifier.Cod => "minecraft:cod",
        EntityIdentifier.EvocationIllager => "minecraft:evocation_illager",
        EntityIdentifier.Endermite => "minecraft:endermite",
        EntityIdentifier.Enderman => "minecraft:enderman",
        EntityIdentifier.ElderGuardian => "minecraft:elder_guardian",
        EntityIdentifier.Drowned => "minecraft:drowned",
        EntityIdentifier.Bat => "minecraft:bat",
        EntityIdentifier.Axolotl => "minecraft:axolotl",
        EntityIdentifier.XpOrb => "minecraft:xp_orb",
        EntityIdentifier.ZombieVillagerV2 => "minecraft:zombie_villager_v2",
        EntityIdentifier.ZombiePigman => "minecraft:zombie_pigman",
        EntityIdentifier.SnowGolem => "minecraft:snow_golem",
        EntityIdentifier.Fireball => "minecraft:fireball",
        EntityIdentifier.ChestBoat => "minecraft:chest_boat",
        EntityIdentifier.Boat => "minecraft:boat",
        EntityIdentifier.ShulkerBullet => "minecraft:shulker_bullet",
        EntityIdentifier.XpBottle => "minecraft:xp_bottle",
        EntityIdentifier.Tnt => "minecraft:tnt",
        EntityIdentifier.SplashPotion => "minecraft:splash_potion",
        EntityIdentifier.LingeringPotion => "minecraft:lingering_potion",
        EntityIdentifier.WitherSkullDangerous => "minecraft:wither_skull_dangerous",
        EntityIdentifier.WitherSkull => "minecraft:wither_skull",
        EntityIdentifier.ThrownTrident => "minecraft:thrown_trident",
        EntityIdentifier.Snowball => "minecraft:snowball",
        EntityIdentifier.FishingHook => "minecraft:fishing_hook",
        EntityIdentifier.EnderPearl => "minecraft:ender_pearl",
        EntityIdentifier.Egg => "minecraft:egg",
        EntityIdentifier.DragonFireball => "minecraft:dragon_fireball",
        EntityIdentifier.ArmorStand => "minecraft:armor_stand",
        EntityIdentifier.LightningBolt => "minecraft:lightning_bolt",
        EntityIdentifier.TripodCamera => "minecraft:tripod_camera",
        EntityIdentifier.TntMinecart => "minecraft:tnt_minecart",
        EntityIdentifier.Minecart => "minecraft:minecart",
        EntityIdentifier.HopperMinecart => "minecraft:hopper_minecart",
        EntityIdentifier.FireworksRocket => "minecraft:fireworks_rocket",
        EntityIdentifier.EyeOfEnderSignal => "minecraft:eye_of_ender_signal",
        EntityIdentifier.CommandBlockMinecart => "minecraft:command_block_minecart",
        EntityIdentifier.ChestMinecart => "minecraft:chest_minecart",
        EntityIdentifier.AreaEffectCloud => "minecraft:area_effect_cloud",
        EntityIdentifier.Creaking => "minecraft:creaking",
        EntityIdentifier.Item => "minecraft:item",
        _ => "minecraft:unknown",
    };
}
